### ISSUE TITLE
Three Stacktraces

### ISSUE THREAD

**Issue by simonbethke** [vbousquet/vpx_lightmapper#2] opened 2022-02-04 06:55 UTC
Just as a little help, here are three stacktraces which most likely are easy to fix/workaround each:

```
Rendering packmaps
Info: No orphaned data-blocks to purge
. Rendering packmap #0 containing 2 bake/light map
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\vpx_lightmapper\__init__.py", line 364, in execute
    vlm_baker.render_packmaps(context)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\vpx_lightmapper\vlm_baker.py", line 1799, in render_packmaps
    print(f'. {obj.vlmSettings.bake_name} has an HDR range of {hdr_range:>5.2} (lightmap: {is_light})')
ValueError: Precision not allowed in integer format specifier

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\vpx_lightmapper\__init__.py", line 364, in execute
    vlm_baker.render_packmaps(context)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\vpx_lightmapper\vlm_baker.py", line 1799, in render_packmaps
    print(f'. {obj.vlmSettings.bake_name} has an HDR range of {hdr_range:>5.2} (lightmap: {is_light})')
ValueError: Precision not allowed in integer format specifier

location: <unknown location>:-1
```
Something is wrong with the print() output. I commented that line and it works. I don't know python syntax but the {hdr_range:>5.2} looks suspicious to me. As if the curly braces should be only around hdr_range or the colon doesn't belong there.

```
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\vpx_lightmapper\__init__.py", line 362, in execute
    vlm_baker.render_all_groups(context)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\vpx_lightmapper\vlm_baker.py", line 543, in render_all_groups
    state, restore_func = setup_light_scenario(context, scenario, group_mask)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\vpx_lightmapper\vlm_baker.py", line 439, in setup_light_scenario
    influence = get_light_influence(scenario[2], group_mask)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\vpx_lightmapper\vlm_baker.py", line 360, in get_light_influence
    influence_radius = light.data.shadow_soft_size + math.log10(light.data.energy) * 250 * global_scale # empirically observed
ValueError: math domain error

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\vpx_lightmapper\__init__.py", line 362, in execute
    vlm_baker.render_all_groups(context)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\vpx_lightmapper\vlm_baker.py", line 543, in render_all_groups
    state, restore_func = setup_light_scenario(context, scenario, group_mask)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\vpx_lightmapper\vlm_baker.py", line 439, in setup_light_scenario
    influence = get_light_influence(scenario[2], group_mask)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\vpx_lightmapper\vlm_baker.py", line 360, in get_light_influence
    influence_radius = light.data.shadow_soft_size + math.log10(light.data.energy) * 250 * global_scale # empirically observed
ValueError: math domain error

location: <unknown location>:-1
```
Here _light.data.energy_ becomes negative. I worked around it for now using _max(0.00001, light.data.energy)_ because I am not sure if the calculation would work for log10(0) which is -infinity.

```
Rendering packmaps
Info: No orphaned data-blocks to purge
. Rendering packmap #0 containing 8 bake/light map
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\vpx_lightmapper\__init__.py", line 364, in execute
    vlm_baker.render_packmaps(context)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\vpx_lightmapper\vlm_baker.py", line 1791, in render_packmaps
    extremas = Image.open(os.path.abspath(path)).getextrema()
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\site-packages\PIL\Image.py", line 2953, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '\\\\shaq - Bakes\\Renders\\Environment - Group 0.exr'

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\vpx_lightmapper\__init__.py", line 364, in execute
    vlm_baker.render_packmaps(context)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\vpx_lightmapper\vlm_baker.py", line 1791, in render_packmaps
    extremas = Image.open(os.path.abspath(path)).getextrema()
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\site-packages\PIL\Image.py", line 2953, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '\\\\shaq - Bakes\\Renders\\Environment - Group 0.exr'

location: <unknown location>:-1
```

**Comment by simonbethke** [comment] 2022-02-04 07:12
If I try to fix the last stacktrace, I run into this one:
```
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\vpx_lightmapper\__init__.py", line 364, in execute
    vlm_baker.render_packmaps(context)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\vpx_lightmapper\vlm_baker.py", line 1791, in render_packmaps
    extremas = Image.open(os.path.abspath(bpy.path.abspath(path))).getextrema()
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\site-packages\PIL\Image.py", line 3008, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file 'C:\\Users\\simon\\Documents\\shaq - Bakes\\Renders\\Environment - Group 0.exr'

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\vpx_lightmapper\__init__.py", line 364, in execute
    vlm_baker.render_packmaps(context)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\vpx_lightmapper\vlm_baker.py", line 1791, in render_packmaps
    extremas = Image.open(os.path.abspath(bpy.path.abspath(path))).getextrema()
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\site-packages\PIL\Image.py", line 3008, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file 'C:\\Users\\simon\\Documents\\shaq - Bakes\\Renders\\Environment - Group 0.exr'

location: <unknown location>:-1
```
That appears to me as if the Pillow Image libraray was not capable of loading exr-files. Could this be the case?

**Comment by vbousquet** [comment] 2022-02-04 21:37
Regarding the bugs:
- first is likely because you have an outdated python. Are you using latest Blender (3.0+) ? The toolkit needs it.
- Second is strange, since light energy is not allowed to be negative
- Third used a path that as been removed (for performance reason).

The code is currently before its initial prealpha release and is in heavy development, It will likely have this type of bugs for the comming weeks. I will try to stabilize a release when the set of base feature will be reached. Sorry for the inconvenience.

**Comment by simonbethke** [comment] 2022-02-04 21:54
Just to let you know: I am totally fine with this kind of code under heavy development. With this kind of bugs. This is just a hobby and the stuff you created here appears to be much more than I expected.
This is no release, no beta, alpha, prealpha... None of this yet. It has too much documentation for the state it is in :D

**Comment by simonbethke** [comment] 2022-02-05 18:23
Regarding the second stack-trace: You get this when rendering "Creature from the black lagoon" for example (got it there right now) also I think "Shaq attack" has this issue with negative light-energy. I wonder if this could also mean that the light energy is not negative but only = 0.

**Comment by vbousquet** [comment] 2022-02-06 00:05
You are right. Stacktrace 2 was closed by https://github.com/vbousquet/vpx_lightmapper/commit/07ef30e6cd1ab271b291ebc1a9a897b4d7430460

**Comment by vbousquet** [comment] 2022-02-06 00:06
Stacktrace 1 was not reproduced
Stacktrace 3 was closed by reimplementing the feature of HDR evaluation

**Closed as completed by vbousquet** 2022-02-06 00:06 UTC

**Comment by simonbethke** [comment] 2022-02-06 09:03
As I am not sure if my mail reached you: I was asking if you are active on any platform that we can use for a chat that is not relatied to any issue :)
